server:
  port: 9001

spring:
  application:
    name: user-service # client-server unique ID

eureka:
  client: # register client-server
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #server-location
