server:
  port: 0 # using random port

spring:
  application:
    name: user-service # client-server unique ID

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

  client: # register client-server
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #server-location
